INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Blood Alloy: Reborn (itch)',19),
	 ('The Dream Self',2),
	 ('Humdrum',12),
	 ('Que Sera Sera Demo',5),
	 ('Aarons Particle Space',4),
	 ('SteamedHams.exe',17),
	 ('Port Blackfire',9),
	 ('Castle Chaos (itch)',8),
	 ('Dark Rogue',19),
	 ('Stealth Fishing',19);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Soul of the Sword',2),
	 ('Dungeons & Clicks',6),
	 ('Bullets!',6),
	 ('BEARZERKERS (itch)',14),
	 ('Frost Final Demo',19),
	 ('Zasa - An AI Story (itch)',5),
	 ('Dungeons & Clicks',20),
	 ('Elemental Warrior',9),
	 ('G Prime Into The Rain',9),
	 ('Bollocks Biker',12);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Uncharted Dreams - Fate of the Miniatures',11),
	 ('p o w e r ARM',5),
	 ('Flable Tip',11),
	 ('Dog World',20),
	 ('GATE',16),
	 ('Dawn',19),
	 ('2V Hoverbike (itch)',2),
	 ('Intelligence: The 314th Clash!',5),
	 ('The Congress of Monsterdom',7),
	 ('Defend Felinearth (itch)',10);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Sudden Strike 4',15),
	 ('Amazing Frog?',2),
	 ('Freddys Vr',4),
	 ('What Do We Eat for Dinner?',16),
	 ('Knight of Days',15),
	 ('Gravity Sketch VR',11),
	 ('Lapis Azurai',13),
	 ('Gary SpringArms - Global Game Jam 17',14),
	 ('They Came Through the Floor',16),
	 ('Gods and Idols',18);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Krampus Quest (itch)',8),
	 ('Aloisius',10),
	 ('Just Feel',2),
	 ('p o w e r ARM',4),
	 ('DISCOCUBE',8),
	 ('Red Entity',9),
	 ('Space Escape',3),
	 ('Flable Tip',5),
	 ('Bullets!',7),
	 ('Corra Snows',14);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('They Came Through the Floor',20),
	 ('Pμcman',1),
	 ('Freddys Vr',18),
	 ('Knight of Days',9),
	 ('Bullet Time',8),
	 ('Race against ferrum gigantes',6),
	 ('Elemental Warrior',9),
	 ('Intelligence: The 314th Clash!',10),
	 ('Excelsior Phase One: Lysandia',5),
	 ('Alleyway Cat Street',1);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Foxglove',16),
	 ('Mirror Protocol',3),
	 ('SteamedHams.exe',8),
	 ('Koji',13),
	 ('Mages of Mystralia',9),
	 ('Rain Game (working title)',4),
	 ('VR Jurassic - Cardboard Park',11),
	 ('CORPUS100',13),
	 ('G Prime Into The Rain',15),
	 ('Lake Serene',10);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Willow (itch)',15),
	 ('Plague venue',1),
	 ('Toilet Tycoon (itch)',13),
	 ('No Danger Is Too Much',2),
	 ('Blasted Bots',8),
	 ('Choice Chamber (itch)',20),
	 ('D/Generation HD',5),
	 ('Dark Rogue',7),
	 ('Frogbike',7),
	 ('Beat Trainer Deluxe',17);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Cosmonet',13),
	 ('Toadies Adventure',13),
	 ('Toadies Adventure',5),
	 ('BOB (TylerC)',1),
	 ('Bullet Time',11),
	 ('Scrapper Showdown',13),
	 ('Papai Noel is Dead',14),
	 ('Legends of Pizza Night',5),
	 ('Toadies Adventure',10),
	 ('GATE',18);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('The Moon Sliver (itch)',17),
	 ('SnowNews',19),
	 ('Mages of Mystralia',2),
	 ('HippiesVsCops',16),
	 ('GATE',15),
	 ('2V Hoverbike (itch)',6),
	 ('A Fraught Place',12),
	 ('Toilet Tycoon (itch)',20),
	 ('Atomicollider',9),
	 ('Act of Mercy',6);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('D/Generation HD',5),
	 ('Star Wrecker Pre-Demo Demo',3),
	 ('Tapsailing',13),
	 ('Mages of Mystralia',17),
	 ('Rain Game (working title)',11),
	 ('Ultra6000',12),
	 ('Stealth Fishing',16),
	 ('Worlds Fastest Pizza (itch)',19),
	 ('Grab Bag',13),
	 ('Soul of the Sword',3);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Lovely Anemone',11),
	 ('DokiDoki fanmade',5),
	 ('Lampette',18),
	 ('The Devils Asshole',10),
	 ('Legends of Pizza Night',10),
	 ('Roru',18),
	 ('Super Capybros. 4 Advance',3),
	 ('Zeus vs Monsters - Math Game',15),
	 ('Toilet Tycoon (itch)',5),
	 ('Twirl',16);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('G Prime Into The Rain',19),
	 ('Sudden Strike 4',3),
	 ('Trapped Demon',6),
	 ('Rain Fall',19),
	 ('EEP Train Simulator Mission',1),
	 ('SteamedHams.exe',7),
	 ('Soul of the Sword',19),
	 ('Willow (itch)',6),
	 ('Frogbike',10),
	 ('Dream Gazer',17);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Graveyard Birds (itch)',8),
	 ('CORPUS100',15),
	 ('Graveyard Birds (itch)',18),
	 ('EEP Train Simulator Mission',9),
	 ('Road to Ruin',10),
	 ('Stealth Fishing',9),
	 ('Micro Island',6),
	 ('Freddys Vr',9),
	 ('Toilet Tycoon (itch)',9),
	 ('Bumble Bots',10);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Tapsailing',2),
	 ('Mages of Mystralia',15),
	 ('Of Guards And Thieves',17),
	 ('White Window',19),
	 ('Circuit Breakers - Demo',12),
	 ('Scuttle at the Shuttle',6),
	 ('FEAR OF VENGEANCE',10),
	 ('Bumble Bots',15),
	 ('Gravity Sketch VR',5),
	 ('The Spaghetti Western Excavation',17);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Corra Snows',2),
	 ('BEARZERKERS (itch)',3),
	 ('The infamous @',19),
	 ('Frogbike',10),
	 ('White Window',16),
	 ('Micro Island',20),
	 ('Shape Master',9),
	 ('Of Guards And Thieves',9),
	 ('Pμcman',11),
	 ('Frost Final Demo',6);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Captain Lycop: Invasion of the Heters',6),
	 ('Que Sera Sera Demo',5),
	 ('Comforting Sounds',16),
	 ('D/Generation HD',10),
	 ('Teh Stream: A Twizted Tale',10),
	 ('Project: Scarf - Demo',1),
	 ('MagiTech City Blitz',7),
	 ('The infamous @',1),
	 ('HippiesVsCops',7),
	 ('Thoughts',20);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Giga Girl (itch)',6),
	 ('Andoran Skye XD (itch)',10),
	 ('Just Feel',16),
	 ('Lapis Azurai',20),
	 ('Captain Lycop: Invasion of the Heters',18),
	 ('Aarons Particle Space',4),
	 ('Dream Gazer',4),
	 ('BEARZERKERS (itch)',2),
	 ('MagiTech City Blitz',8),
	 ('Roguefort',18);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Dungeons & Clicks',9),
	 ('Toilet Tycoon (itch)',8),
	 ('MAINFRAME',17),
	 ('Bullet Time',12),
	 ('MagiTech City Blitz',4),
	 ('Starjunk DSSR',17),
	 ('BOB (TylerC)',6),
	 ('Papi Commando - 100% Free Version PC !',3),
	 ('Sepia and the Magical Book',5),
	 ('Ultra6000',1);
INSERT INTO gamestore.game (game_name,developer_id) VALUES
	 ('Frost Final Demo',17),
	 ('La Boîte Noire',8),
	 ('Cosmonet',1),
	 ('Postman',9),
	 ('Drawn In',11),
	 ('What Do We Eat for Dinner?',18),
	 ('SEUM: Speedrunners from Hell',6),
	 ('Fading Light: Descent',4),
	 ('Humdrum',13);
